services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: svetikovia-netilogy-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - monitoring-stack
    restart: always


  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: svetikovia-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - monitoring-stack
    depends_on:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: svetikovia-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 81:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-stack
    depends_on:
      - prometheus
    restart: unless-stopped


volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring-stack:
     driver: bridge
     ipam:
       config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

